# Generated by Django 3.1.7 on 2021-02-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_vs_chaos', models.CharField(choices=[('Lawful', 'Lawful'), ('Neutral', 'Neutral'), ('Chaotic', 'Chaotic')], default='Neutral', max_length=7)),
                ('good_vs_evil', models.CharField(choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Evil', 'Evil')], default='Neutral', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='core.alignment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alignment',
            constraint=models.UniqueConstraint(fields=('law_vs_chaos', 'good_vs_evil'), name='unique_alignment'),
        ),
    ]
